### PR TITLE
Problem and improvement in Divide plugin

### PR DESCRIPTION
**Pull request by lmhmhl**
Existing problems:
During the health check of upstreamlist by divide plug-in, when a service node is down, upstreamlist will automatically reject the inaccessible nodes. When the hung up node restarts, soul will not perceive that the previously hung node is available again, or send all requests to the nodes in divideupstream list that removed the previously hung nodes. At this time, it is necessary to synchronize manually in admin to make sure that the new node is available again.
improvement:
In the divide plug-in, add an upstream of type concurrenchashmap_ MAP_ Temp, used for node health check, stores accessible nodes. UPSTREAM_ MAP Only responsible for cache synchronization to keep the data consistent with admin. Therefore, if any node is found to be inaccessible during the inspection, the_ MAP_ The upstreamlist in temp is modified, and upstream_ Map is always synchronized with the configuration of admin. If a node that was previously down is available again, and there is no need to synchronize in admin, Saul will automatically perceive that this node is available. Therefore, you need to click the sync button only when the admin modifies the divideupstream of a selector.
中文版
存在问题：
Divide 插件在对upstreamlist健康检查时，当一个服务的节点挂掉，upstreamlist会自动剔除不可访问的节点，当挂掉的节点重新启动，soul不会感知到之前挂掉的节点重新可用了，还是将请求全发给剔除掉之前挂掉节点的divideUpstream list中的节点。这时需要手动在admin进行同步，才能使soul网关感知到新节点又是可用了。
改进：
在Divide插件中，添加一个ConcurrentHashMap类型的UPSTREAM_MAP_TEMP，用于做节点的健康检查，存储的是可以访问的节点。UPSTREAM_MAP只负责进行缓存同步，保持和admin的数据一致。因此，在检查过程中如果发现有节点不可访问，会对UPSTREAM_MAP_TEMP中的upstreamlList进行修改，而UPSTREAM_MAP始终和admin的配置保持同步，如果此时有一个之前挂掉的节点重新可用了，不需要在admin中进行同步操作，soul会自动感知到此节点可用。所以只有当在admin修改了某个selector的divideUpstream时，才需要点击同步按钮。

### CODE REVIEW

**Comment by yu199195** [comment]
when node restart,   can register to soul-admin,  finally  sync to soul

**Comment by tydhot** [comment]
I think if you want to do some improvement like this, you'd better open an issue discuss with us

**Comment by tydhot** [comment]
can you commit after install successfully in your personal pc

**Comment by lmhmhl** [comment]
> can you commit after install successfully in your personal pc

MY BAD

**Comment by lmhmhl** [comment]
> when node restart, can register to soul-admin, finally sync to soul



> when node restart, can register to soul-admin, finally sync to soul

If the suspended node restarts, you need to manually click sync to synchronize the data of the admin to the soul,
When do I need sync?
If I modify the upstream of the selector, I must click the sync button to synchronize the data in the soup,
If a node in upstream is not accessed during a health check because of network jitter, the upstreamlist is removed. After a period of time, the network is stable and can be accessed again. In this case, you need to manually click the sync button to synchronize. However, the occurrence of the situation is unpredictable. In order to improve the high availability of the system, I mean Yes, an upstreamlist is added to dynamically delete the unreachable nodes during health check. At the beginning, the upstreamlist is used to keep consistent with the configuration in admin, and the objects for health check each time are unchanged. The source code used to perform health check on the basis of deleting the upstream list of unreachable nodes. The nodes that have been removed will not be checked again. After the change, the list for each node health check remains unchanged, the same as in admin. I hope I make it clear, thank you.

什么时候需要sync？
如过我对selector的upstream进行修改，那么在改完之后必须要点击sync按钮，对soul中的数据进行同步，
如果upstream中的节点因为网络抖动，在一次健康检查时，没有访问到，导致被移除了upsteamList，过一段时间之后，网络恢复稳定，又可以访问到了，这种情况需要也需要手动点击sync按钮进行同步，然而情况的发生时不可预知的，为了提高系统的高可用性，我的意思是，添加一个upstreamList用于在健康检查时动态的删除不可达的节点，而一开始的那个upstreamlist用于和admin中配置的保持一致，保持每次进行健康检查的对象是不变的。之前源码是在删除不可达节点的upstreamlist的基础上再进行健康检查，那已经被剔除的节点，就不会再被检查到了，改动之后每次进行节点健康检查的list保持不变，和admin中一样。希望我说明白了，谢谢。

**Comment by yu199195** [comment]
@lmhmhl  We're having a checkup

**Comment by tydhot** [comment]
I hope next time you can open an issue first to discuss about it. I 'm afraid it will be some conflict with #497 .I think we need more discussion about all above this.

**Comment by yu199195** [comment]
Is the code you submitted a reference to our previous version ?

**Comment by lmhmhl** [comment]
> Is the code you submitted a reference to our previous version ?

sorry, I update the branch right now

**Comment by tydhot** [comment]
Add my WeChat .And my WeChat id is same as my GitHub id.

**Comment by lmhmhl** [comment]
> Add my WeChat .And my WeChat id is same as my GitHub id.

Ok, thank u

**Comment by lmhmhl** [comment]
> I hope next time you can open an issue first to discuss about it. I 'm afraid it will be some conflict with #497 .I think we need more discussion about all above this.

I think it is not the same.

**Comment by lmhmhl** [comment]
> I hope next time you can open an issue first to discuss about it. I 'm afraid it will be some conflict with #497 .I think we need more discussion about all above this.

n my opinion, although issue497 tries to solve the problem of whether to add it to the list by setting the state of the node each time when health check is performed on the node, but upstream_ MAP
It is a singleton, that is, it is globally unique. Each selector is traversed through the scheduled method, and then the upstreamlist is passed into the check method. However, this upstreamlist is the result of the last health check, so it may be inconsistent with the information configured in the admin. That is, nodes that were previously inaccessible will not be checked at the next health check.
翻译：我认为issue497虽然尝试解决每次对节点进行健康健康检查时，通过设置节点的状态，来控制每次是否要添加到list中，但是，UPSTREAM_MAP是一个单例，也就是说，是全局唯一的，通过在scheduled方法中对每一个selector进行遍历，然后将upstreamlist传入check方法，但是这个upstreamlist是上次进行健康检查的结果，可能有一些暂时不可达的节点删除了，所以和admin中配置的信息可能不一致。也就是说，之前不可达的节点在下一次健康检查时不会进行检查。

**Comment by lmhmhl** [comment]
> I hope next time you can open an issue first to discuss about it. I 'm afraid it will be some conflict with #497 .I think we need more discussion about all above this.
I would also like to remind you that the writing method like 497 has thread safety problems, because the state setting is not an atomic operation. It is possible that a node is unreachable. When the state is set to false, other threads get the state and get the previous state
我还想提醒一下，497那样的写法是有线程安全问题的，因为状态的设置不是原子操作，完全可能某个节点是不可达的，在设置状态为false时，其他线程获来获取了状态，取到的是之前的状态

**Review by yu199195 — APPROVED** [review]

**Pull request merged**
