### PR TITLE
debug plugin, print request and response info

### PR DESCRIPTION
**Pull request by xxd763795151**
// Describe your PR here; eg. Fixes #issueNo
Provide a debug plugin, that can print request and response info, as follows:
`
2021-04-28 20:30:16 [reactor-http-kqueue-1] INFO  org.dromara.soul.plugin.debug.DebugPlugin - Print debug info: 
Request Uri: http://localhost:9195/http/order/path/1/xux?aa=bbb
Request Method: GET

[Request Headers Start]
X-From: all
X-AUTH-SOURCE: SSO
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: d9f2ead3-1a1b-4549-b4-8ff7bee421
Host: localhost:9195
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 42
Cookie: zg_did=%7B%22did%25884-0f1d8976e2d8a4-161d-384000-177eb09638d%22%7D; 
[Request Headers End]

[Query Params Start]
aa: bbb
[Query Params End]

[Request Body Start]
{
    "id": "1223",
    "name": "testss"
}
[Request Body End]

Response Code: 200 OK

[Response Headers Start]
transfer-encoding: chunked
Content-Type: application/json
Content-Length: 44
[Response Headers End]

[Response Body Start]
{"id":"1","name":"hello world restful: xux"}
[Response Body End]
`
There has not the sql for insert debug plugin. The plugin name is 'debug', that can add by the admin console.

Make sure that:

- [ ] You have read the [contribution guidelines](https://dromara.org/projects/soul/contributor/).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by yu199195** [comment]
this is  mean？

**Comment by xxd763795151** [comment]
> this is mean？

Sorry, there are 2 files forgetting to attach license.

It can use to print request detaile info(include request head,request params and request body(such as post method) and respsone info (response head and response body), if config the rule on the debug plugin.It can use on the online environment.

**Comment by yu199195** [comment]
can you rename loggingPlugin

**Comment by xxd763795151** [comment]
> can you rename loggingPlugin?
> 
> and you will be add the plugin doc。

Ok, I adjust it.

**Pull request merged**
