### PR TITLE
Add test cases for ZookeeperConfiguration and ZookeeperProperties. #508

### PR DESCRIPTION
**Pull request by fengzhenbing**
Make sure that:

- [x] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Review by dengliming — CHANGES_REQUESTED** [review]
Hey~ Thanks for your contribution. Most of it looks good. Here are a few suggestions.
1. We should only test configuration here. No need to start a zkServer.
2. Please extends this class `AbstractConfigurationTest `

BTW, here is a simple example. [https://github.com/dromara/soul/blob/master/soul-admin/src/test/java/org/dromara/soul/admin/config/HttpSyncPropertiesTest.java](https://github.com/dromara/soul/blob/master/soul-admin/src/test/java/org/dromara/soul/admin/config/HttpSyncPropertiesTest.java)

**Comment by fengzhenbing** [comment]
> Hey~ Thanks for your contribution. Most of it looks good. Here are a few suggestions.
> 
> 1. We should only test configuration here. No need to start a zkServer.
> 2. Please extends this class `AbstractConfigurationTest `
> 
> BTW, here is a simple example. https://github.com/dromara/soul/blob/master/soul-admin/src/test/java/org/dromara/soul/admin/config/HttpSyncPropertiesTest.java
Thanks for your review . I will try your suggestions.

**Comment by dengliming** [comment]
Missing test for `ZookeeperConfiguration`

**Comment by fengzhenbing** [comment]
> Missing test for `ZookeeperConfiguration`

Hello. When I  test ZookeeperConfiguration, I get a ZkClient instance which need to start a zkServer.
`  org.I0Itec.zkclient.ZkClient line 157      connect(connectionTimeout, this);`
How can I test it wihtout  starting a zkServer.
Could you give me some suggestions?

Here is my code:
` public final class ZookeeperConfigurationTest extends AbstractConfigurationTest {

    private final AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext();

    private final String[] inlinedProperties = new String[]{
            "soul.sync.zookeeper.url=127.0.0.1:21810",
            "soul.sync.zookeeper.sessionTimeout=5000",
            "soul.sync.zookeeper.connectionTimeout=2000",
            "soul.sync.zookeeper.serializer=org.I0Itec.zkclient.serialize.SerializableSerializer",
    };

    @Test
    public void testOnMissingBean() {
        // init zkClient by ZookeeperConfiguration
        load(ZookeeperConfiguration.class, inlinedProperties);
        ZkClient zkClient = (ZkClient) this.context.getBean("zkClient");
        assertNotNull(zkClient);
    }

    @Test
    public void testOnExistBean() {
        // verify zkClient by ZookeeperConfiguration
        load(CustomZkClientConfiguration.class, inlinedProperties);
        Boolean isExistZkClient = this.context.containsBean("zkClient");
        assertFalse(isExistZkClient);

        // get customZkClient
        ZkClient customZkClient = (ZkClient) this.context.getBean("customZkClient");
        assertNotNull(customZkClient);
    }

    @EnableConfigurationProperties(ZookeeperProperties.class)
    static class CustomZkClientConfiguration {

        @Bean
        @ConditionalOnMissingBean(ZkClient.class)
        public ZkClient customZkClient(final ZookeeperProperties zookeeperProp) {
            return new ZkClient(zookeeperProp.getUrl(), zookeeperProp.getSessionTimeout(), zookeeperProp.getConnectionTimeout());
        }
    }
}`

**Comment by dengliming** [comment]
You can start a zkServer If it's necessary.

**Comment by fengzhenbing** [comment]
Thanks. I'll try it;

**Review by yu199195 — APPROVED** [review]

**Review by dengliming — APPROVED** [review]

**Pull request merged**
