### PR TITLE
support Nacos config authentication for sync data

### PR DESCRIPTION
**Pull request by xxd763795151**
// Describe your PR here; eg. Fixes #issueNo

Make sure that:

- [ ] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Comment by yu199195** [comment]
@xxd763795151  hi, why need authentication for nacos

**Comment by xxd763795151** [comment]
> @xxd763795151 hi, why need authentication for nacos

@yu199195 our nacos server deploy on ali cloud , and turn on authentication(nacos.core.auth.enabled=true) for security. But soul have not support config about authenticaion.So it will occur as following when sync data: 
```
There was an unexpected error (type=Forbidden, status=403).
```

**Review by dengliming — APPROVED** [review]

**Comment by yu199195** [comment]
thanks you very much,  if Use by your company please registration in this : #68

**Comment by xxd763795151** [comment]
> @xxd763795151 thanks you very much, if Use by your company please registration in this : #68
@yu199195 Ok, thank your for dealing with it so quickly. We want to use soul as our new gateway and we are testing. If we make sure to use it , I will register it lately.

**Pull request merged**
