### PR TITLE
Add test case for RuleCntroller of soul-admin

### PR DESCRIPTION
**Pull request by shijie666**
Make sure that:

- [x] You have read the [contribution guidelines](https://dromara.org/en-us/docs/soul/contributor.html).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `mvn clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

**Review by dengliming — COMMENTED** [review]
Can you also add a test for `queryRules ` method?

**Comment by shijie666** [comment]
> 
> 
> Can you also add a test for `queryRules ` method?

Please wait a moment. I'll try

**Review by dengliming — CHANGES_REQUESTED** [review]
Can you also add a test for queryRules method?

**Comment by shijie666** [comment]
> 
> 
> Can you also add a test for queryRules method?

Sorry, I have been trying to add a test for queryRules method, but there have been problems.

**Comment by dengliming** [comment]
Try like this [https://github.com/dromara/soul/blob/master/soul-admin/src/test/java/org/dromara/soul/admin/controller/SelectorControllerTest.java#L83-L91](https://github.com/dromara/soul/blob/master/soul-admin/src/test/java/org/dromara/soul/admin/controller/SelectorControllerTest.java#L83-L91)

**Comment by shijie666** [comment]
> 
> 
> Try like this https://github.com/dromara/soul/blob/master/soul-admin/src/test/java/org/dromara/soul/admin/controller/SelectorControllerTest.java#L83-L91

Thank you, test case for queryRules method added

**Review by dengliming — APPROVED** [review]

**Pull request merged**
